log:
  level: info # LOG LEVEL: error, warn, info, http, verbose, debug, silly
  dir: ./data/log # Directory to store log files

telegram:
  whitelabel: "@userkcepu77_bot" # To display the whitelabel name in the main menu
  channels: # Fitur masih dalam pengembangan, tidak digunakan saat ini
    - "@userkcepu77_bot" # Channel yang harus diikuti oleh client sebelum bisa mengakses bot
    # Tambahkan lebih dari satu channel jika diperlukan, pisahkan dengan koma
  admin_ids: # Daftar Master Admin dengan akses penuh untuk mengelola bot dan co-admin
    - 7109036965 # Ganti dengan ID Telegram Anda
    bot:
    token: 8011173029:AAGWmprTFOBaEmYHLAD7_tYBnud4SvVzxVo # Ganti dengan token bot Telegram Anda
    api:
      protocol: http
      host: nginx
      port: 80
  botnotif:
    token: 7874472571:AAFItOL8vjbfbPDNB_k588WxsLllWiioNZo # Ganti dengan token bot notifikasi Telegram Anda
    api:
      protocol: http
      host: nginx
      port: 80
